"""Evaluate a trained zone model on a session it never saw, and write the results report.

    python training/evaluate.py --model models/zone_model.pt --test dataset/test

Prints overall accuracy and per-class precision / recall / F1, measures CPU inference
time, and saves into results/<model name>/:
    eval_confusion_matrix.png   what was confused with what
    failures.png                the 12 most confident WRONG predictions (failure analysis)
    eval.json                   all numbers
Then (re)writes results/RESULTS.md from every results/*/metrics.json + eval.json.
It uses the app's own ZoneClassifier, so it tests exactly what runs in main.py.
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

import cv2
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from training.train_zone import confusion, per_class_metrics, plot_confusion  # noqa: E402
from vision.zone_classifier import ZoneClassifier  # noqa: E402

IMAGE_EXTS = (".jpg", ".jpeg", ".png")
TILE_W, TILE_H, CAPTION_H = 240, 180, 44


def load_test_images(test_dir, class_names):
    """[(path, true_label_index)] for every image in test_dir/<class>/."""
    items = []
    for label, name in enumerate(class_names):
        folder = Path(test_dir) / name
        if not folder.is_dir():
            print(f"  warning: no '{name}' folder in {test_dir}")
            continue
        items += [(str(p), label) for p in sorted(folder.iterdir()) if p.suffix.lower() in IMAGE_EXTS]
    extra = {p.name for p in Path(test_dir).iterdir() if p.is_dir()} - set(class_names)
    if extra:
        print(f"  warning: folders the model does not know are skipped: {sorted(extra)}")
    return items


def failure_grid(failures, class_names, cols=4):
    """One image with the most confident wrong predictions and their labels."""
    if not failures:
        img = np.full((120, 600, 3), 255, np.uint8)
        cv2.putText(img, "No wrong predictions on the test session", (15, 65),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 120, 0), 2, cv2.LINE_AA)
        return img
    rows = (len(failures) + cols - 1) // cols
    grid = np.full((rows * (TILE_H + CAPTION_H), cols * TILE_W, 3), 255, np.uint8)
    for i, (path, true_i, pred_i, conf) in enumerate(failures):
        r, c = divmod(i, cols)
        x, y = c * TILE_W, r * (TILE_H + CAPTION_H)
        tile = cv2.imread(path)
        if tile is not None:
            grid[y:y + TILE_H, x:x + TILE_W] = cv2.resize(tile, (TILE_W, TILE_H))
        cv2.putText(grid, f"true: {class_names[true_i]}", (x + 6, y + TILE_H + 18),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 120, 0), 1, cv2.LINE_AA)
        cv2.putText(grid, f"pred: {class_names[pred_i]} {conf:.2f}", (x + 6, y + TILE_H + 38),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 200), 1, cv2.LINE_AA)
    return grid


def time_inference(clf, frame, runs=100):
    """Average CPU milliseconds for one prediction (after one warm-up run)."""
    clf.predict(frame)
    start = time.perf_counter()
    for _ in range(runs):
        clf.predict(frame)
    return (time.perf_counter() - start) / runs * 1000


def top_confusions(cm, class_names, n=3):
    """The biggest off-diagonal cells: [(true, predicted, count)]."""
    pairs = [(cm[t][p], class_names[t], class_names[p])
             for t in range(len(class_names)) for p in range(len(class_names)) if t != p and cm[t][p]]
    return [(t, p, int(c)) for c, t, p in sorted(pairs, reverse=True)[:n]]


def pct(x):
    return "-" if x is None else f"{x:.1%}"


def write_report(results_dir):
    """results/RESULTS.md from all runs' metrics.json (training) and eval.json (this script)."""
    results_dir = Path(results_dir)
    rows, notes, evaluated = [], [], False
    for run_dir in sorted(p for p in results_dir.iterdir() if p.is_dir()):
        m_file, e_file = run_dir / "metrics.json", run_dir / "eval.json"
        if not m_file.exists() and not e_file.exists():
            continue
        m = json.loads(m_file.read_text()) if m_file.exists() else {}
        e = json.loads(e_file.read_text()) if e_file.exists() else {}
        evaluated = evaluated or bool(e)
        reg = m.get("regularised")
        label = "with regularisation" if reg else ("without regularisation" if reg is False else "?")
        ms = e.get("inference_ms")
        rows.append(f"| {run_dir.name} | {label} | {pct(m.get('train_acc'))} | {pct(m.get('val_acc'))} "
                    f"| {pct(e.get('accuracy', m.get('test_acc')))} | {'-' if ms is None else f'{ms:.1f}'} |")
        for t, p, c in e.get("top_confusions", []):
            notes.append(f"- **{run_dir.name}:** {c} test photo(s) of **{t}** were predicted as **{p}**.")

    lines = [
        "# Zone classifier results",
        "",
        "Generated by `training/evaluate.py` from `results/*/metrics.json` and `eval.json`.",
        "Test accuracy is measured on the `test` session, which was never used for training.",
        "",
        "| Run | Regularisation | Train acc | Val acc | Test acc | CPU ms / image |",
        "|---|---|---|---|---|---|",
        *rows,
        "",
        "Overfitting = the gap between train and test accuracy. Compare the two runs.",
        "",
        "## What went wrong",
        "",
        *(notes or ["- No wrong predictions on the test session." if evaluated
                    else "- Not evaluated yet (run training/evaluate.py on the test session)."]),
        "",
        "Look at `failures.png` of each run and describe the pattern in simple words, e.g.",
        "\"Door and Window get confused when the curtain is open\" or \"blurry frames become Other\".",
        "_(Team: write your observations here after looking at the failure grid.)_",
        "",
    ]
    (results_dir / "RESULTS.md").write_text("\n".join(lines), encoding="utf-8")
    return results_dir / "RESULTS.md"


def main():
    ap = argparse.ArgumentParser(description="Evaluate the MAPPAL zone classifier")
    ap.add_argument("--model", default="models/zone_model.pt")
    ap.add_argument("--test", default="dataset/test", help="folder with <class>/ subfolders")
    ap.add_argument("--results", default="results")
    args = ap.parse_args()

    clf = ZoneClassifier(args.model)
    names = clf.class_names
    items = load_test_images(args.test, names)
    if not items:
        sys.exit(f"No test images found in {args.test}")
    print(f"Evaluating {args.model} on {len(items)} images from {args.test} ...")

    y_true, y_pred, wrong = [], [], []
    for path, true_i in items:
        label, conf = clf.predict(cv2.imread(path))
        pred_i = names.index(label)
        y_true.append(true_i)
        y_pred.append(pred_i)
        if pred_i != true_i:
            wrong.append((path, true_i, pred_i, conf))

    cm = confusion(y_true, y_pred, len(names))
    per_class = per_class_metrics(cm, names)
    acc = float(np.mean(np.array(y_true) == np.array(y_pred)))
    ms = time_inference(clf, cv2.imread(items[0][0]))

    print(f"\nOverall accuracy: {acc:.1%}  ({len(items) - len(wrong)}/{len(items)} correct)")
    print(f"{'class':<10}{'precision':>10}{'recall':>9}{'F1':>7}{'photos':>8}")
    for name, m in per_class.items():
        print(f"{name:<10}{m['precision']:>10.2f}{m['recall']:>9.2f}{m['f1']:>7.2f}{m['support']:>8}")
    print(f"\nCPU inference: {ms:.1f} ms per image (average of 100 runs on this laptop)")

    out_dir = Path(args.results) / Path(args.model).stem
    out_dir.mkdir(parents=True, exist_ok=True)
    plot_confusion(cm, names, out_dir / "eval_confusion_matrix.png")
    wrong.sort(key=lambda w: w[3], reverse=True)
    cv2.imwrite(str(out_dir / "failures.png"), failure_grid(wrong[:12], names))
    (out_dir / "eval.json").write_text(json.dumps({
        "model": args.model, "test_dir": args.test, "images": len(items),
        "accuracy": round(acc, 4), "per_class": per_class, "confusion_matrix": cm.tolist(),
        "inference_ms": round(ms, 2), "top_confusions": top_confusions(cm, names),
    }, indent=2))
    report = write_report(args.results)
    print(f"Saved {out_dir}/eval_confusion_matrix.png, failures.png, eval.json and {report}")
    if acc >= 0.99:
        print("Note: 99%+ on the test session is suspicious - is the test session too similar"
              " to the training walk? Collect it at another time / light / angle.")


if __name__ == "__main__":
    main()
